name = "quartz-online"
compatibility_date = "2024-01-01"

# Pages 项目配置 (Next.js 静态导出输出目录)
pages_build_output_dir = "out"

[env.production]
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
ENVIRONMENT = "production"
